"""Write the research report using actual saved outputs only."""
from common import *
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from evaluate import figure_save

def read(name): return json.loads((OUT/name).read_text())
def fmt(v): return 'unavailable' if v is None else f'{v:.4f}'

def main():
    d=cohort(); selection=read('selection.json'); metrics=read('metrics.json'); ex=read('explanation_summary.json')
    ab=read('ablations.json'); perm=read('permutation_importance.json'); fair=read('fairness_availability_and_diagnostics.json')
    splits=read('split_summary.json'); chosen=selection['selected_model']; m=metrics[chosen]['point']; ci=metrics[chosen]['ci_95_user_cluster_bootstrap']
    first_seen=d.groupby('user_id').timestamp.min().dt.quarter.value_counts().sort_index().to_dict()
    save_json(OUT/'temporal_feasibility.json',{'users_first_seen_by_quarter':first_seen,
        'interpretation':'new-user chronological evaluation late in the year has too few users; grouped contemporaneous study only'})
    lines=['# Synthetic UPI post-transaction fraud demonstration', '', 'Analysis date: 8 September 2026.', '',
        '**This is a methodological demonstration on supplied synthetic data, not empirical evidence about Indian borrowers, real fraud, credit default or lending fairness.** The user approved adapting the original credit-default study because repayment outcomes are absent.', '',
        '## Evidence and paper assessment', '',
        'The supplied paper, *Bridging the Financial Divide: AI-Driven Credit Scoring Models for Underserved Populations* (IOSR-JEF, 2026, pp. 49–62, DOI 10.9790/5933-1701034962), synthesizes literature and proposes a conceptual framework. Sections IV and VIII discuss prediction, preprocessing, explanations, fairness and governance; Figure 3 links an AI scoring engine to data, fairness/explainability, governance and credit decisions. It does not specify an original training sample, default horizon, split, fixed architecture or hyperparameter recipe.', '',
        'Its discussion includes logistic regression, forests, boosting and neural networks; normalization, RFE, PCA and SMOTE; accuracy, precision, recall, F1 and ROC-AUC; and SHAP/LIME. The proposed design assumes alternative signals and repayment outcomes are available and meaningful, with information suitable for fairness evaluation and ongoing monitoring. Those assumptions are not met by this workbook. Literature performance claims are not our results, and are not treated as a benchmark. The paper is not an India-specific validation study. Some references support claims outside their apparent subject area; primary studies would need verification before relying on reported accuracies.', '',
        'Source: [original paper](../AI%20Credit%20Scoring.pdf), especially PDF pages 8, 10–11. The relevant method/framework pages were visually inspected. [Original workbook](../transactions_UPI%20.xlsx) was read only. Full SHA256 hashes are in audit.json.', '',
        '## Data and feasibility', '',
        'The original workbook has 20,000 rows, 30 columns, 2,000 users and 763 positive fraud labels (3.815%). There is no default label, repayment horizon, origination date, genuine bureau score, gender, income tier or documented rural/urban attribute. It has repeated users, not documented borrowers. Source is Kaggle according to the user; URL, licence, generator, fraud assignment rule and timestamp timezone are unknown.', '',
        'Missingness: time_since_last_txn_min 2,335 (11.675%), transaction_velocity 393 (1.965%), amount_deviation_score 367 (1.835%); the other 27 columns have no detected missing values. No duplicate full rows were found. Dates span 1 January–30 December 2024. See [complete column audit](data_audit.md) and [provisional dictionary](data_dictionary.json). Zero detected missingness does not prove valid or realistic values.', '',
        f'The completed-attempt cohort has {len(d):,} rows and {int(d.is_fraud.sum()):,} positive labels ({d.is_fraud.mean():.3%}). Success and Failed are treated as terminal attempts; 557 Pending rows are excluded. A failed attempt is not a settled payment. This explicit cohort assumption needs source confirmation. Fraud ascertainment timing is unknown; the experiment predicts a recorded label from presumed event-time descriptors, not a future outcome.', '',
        'Actual modeled groups are amount, timing (hour/weekday recomputed from timestamp), payment context (receiver type, transaction type, payment app), and device type. Category names are retained literally. Recharge does not provide telecom usage history, Bill Payment does not establish utility arrears, and P2M does not establish e-commerce behavior. City tier means city category and KYC means identification status according to the user; both remain outside prediction features.', '',
        '## Experimental design', '',
        '| Partition | Rows | Users |', '|---|---:|---:|']
    for name,v in splits.items(): lines.append(f"| {name} | {v['rows']:,} | {v['users']:,} |")
    lines += ['', f'First-seen users by quarter: {first_seen}. Only one first appears in Q4. The study therefore uses stratified user-grouped partitions rather than a late chronological/new-user test with negligible coverage. Calendar periods overlap; no future-time generalization is claimed. Receivers can recur, so this is not a network-disjoint study.', '',
        'Pipelines fit imputation, scaling and one-hot encoding inside training folds. Each model has four hyperparameter settings on the same three stratified grouped training folds. Sigmoid calibration uses only grouped training folds; validation Brier selects raw/calibrated output. Validation average precision selects the final model. Thresholds maximize validation F1, breaking ties toward fewer alerts. No resampling or feature selection is used. Models remain fitted on training data; validation is not silently added to training.', '',
        'Identifiers, status, post-transaction balances, city/KYC, and undocumented historical or security scores are excluded from primary predictors. This avoids relying on unverified retrospective aggregates, but does not prove independence from the unknown synthetic label-generation process. Final test predictions are not used to tune models or thresholds. All ablation configurations were fixed before test evaluation.', '',
        '## Actual held-out predictive results', '',
        'PR-AUC below means **average precision**, not trapezoidal PR area. All measurements are on synthetic completed attempts from unseen users.', '',
        '| Model | ROC-AUC | AP | Precision | Recall | F1 | Brier | Alert rate |', '|---|---:|---:|---:|---:|---:|---:|---:|']
    for name in ['prior_baseline','logistic','random_forest']:
        mm=metrics[name]['point']; lines.append('| '+name+' | '+' | '.join(fmt(mm[k]) for k in ['roc_auc','pr_auc_average_precision','precision','recall','f1','brier','alert_rate'])+' |')
    lines += ['', f'Validation selected **{chosen}**. Its test ROC-AUC is {m["roc_auc"]:.4f}, with 95% user-cluster bootstrap interval [{ci["roc_auc"]["lower"]:.4f}, {ci["roc_auc"]["upper"]:.4f}]. Average precision is {m["pr_auc_average_precision"]:.4f}, interval [{ci["pr_auc_average_precision"]["lower"]:.4f}, {ci["pr_auc_average_precision"]["upper"]:.4f}]. The ROC-AUC interval includes 0.5. Performance is weak; this is not evidence for deployment.', '',
        f'At its frozen threshold {m["threshold"]:.6f}, the selected model flags {m["tp"]+m["fp"]:,} of {len(np.load(private_dir()/"test_predictions.npz")["y"]):,} transactions: {m["tp"]} true positives and {m["fp"]} false positives, with {m["fn"]} missed fraud labels and {m["tn"]} true negatives. A flag means referral for post-event review. These are not loan decisions. Validation F1 supplies no business-cost justification for this workload.', '',
        'The constant-prior baseline flags all events at its validation-F1 threshold; this is an expected limitation of that threshold objective, not a useful review policy. At threshold 0.5, a low-prior constant model would flag none. Brier scores should be compared with the prevalence baseline: a small absolute value in a rare-event dataset does not by itself show a useful detector.', '',
        'Intervals use 500 user-cluster resamples, retaining all rows for each sampled user. They condition on the fitted models and one partition, do not include model-fitting uncertainty, and do not justify inference outside the synthetic data. Full metrics, confusion counts and intervals are in metrics.json.', '',
        '![Held-out performance](figures/performance.png)', '', '![Confusion matrices](figures/confusion_matrices.png)', '',
        '## Signal-group diagnostics', '',
        'Fixed-configuration raw-random-forest ablation measures full-model AP minus AP after removing a group. Positive values favor retaining the group. These do not compare UPI against missing telecom/utility/e-commerce datasets.', '',
        '| Removed group | AP difference | Paired 95% user-cluster interval | Joint permutation AP drop |', '|---|---:|---|---:|']
    for group,v in ab.items(): lines.append(f"| {group} | {v['ap_full_minus_removed']:.4f} | [{v['ci_95'][0]:.4f}, {v['ci_95'][1]:.4f}] | {perm[group]['mean_ap_drop']:.4f} |")
    lines += ['', 'Timing has the largest positive ablation difference in this run. This describes model dependence within synthetic data; it is not causal evidence about Indian fraud. The four intervals are exploratory and not adjusted for multiple comparisons. Permutation standard deviations measure shuffle variability, not sampling uncertainty. Correlation and substitutability can change both ablation and permutation rankings; grouped permutation preserves within-group structure but not cross-group dependence. Removing a group does not trigger new tuning, so the comparison is conditional on the full-model configuration.', '',
        '![Group permutation](figures/group_importance.png)', '',
        '## Explanation comparison', '',
        'Both models use the same 12 test score-quantile cases and three repetitions. SHAP background is 100 training rows. LIME receives the same number of prediction rows as SHAP in each matched run (the saved median is 23,760). Timings include explainer setup after prediction warm-up; first-call compilation and machine load can still affect them. These are selected cases, not a prevalence-weighted population sample.', '',
        '| Model | Method | Median seconds | Median audit R2 | Median audit RMSE | Repeat top-3 Jaccard |', '|---|---|---:|---:|---:|---:|']
    for name,v in ex['models'].items():
        for method in ['SHAP','LIME']:
            mm=v[method]; lines.append(f"| {name} | {method} | {mm['seconds']:.4f} | {mm['audit_neighborhood_r2']:.4f} | {mm['audit_neighborhood_rmse']:.6f} | {mm['mean_repeat_top3_jaccard']:.4f} |")
    lines += ['', 'Audit R2/RMSE evaluate each additive approximation on a shared independent donor-masking neighborhood of 300 events. This is a diagnostic chosen for this experiment, not a universal explanation-quality test and not SHAP’s native objective. SHAP attributes a conditional coalition expectation under its masker, while the audit samples specific donor events; irreducible donor variation and feature interactions can reduce its R2. LIME uses Gaussian numeric perturbations and categorical matches, so its fit neighborhood differs from the audit neighborhood. Negative R2 is preserved rather than hidden.', '',
        'LIME has higher audit fidelity for the calibrated logistic model in this run, but negative median audit R2 for the forest. Both methods can produce stable influential-feature lists even for weak predictive models. SHAP reconstructs the explained point to numerical precision; that identity does not establish local fidelity or truth. LIME numeric coefficients are per training standard deviation, while SHAP values are contributions relative to its background; their magnitudes and signs are not interchangeable. Between-method top-3 overlap is descriptive only. No bureau model is present, so no alternative-versus-bureau explanation comparison is possible.', '',
        '![SHAP case summary](figures/explanation_importance.png)', '',
        '## Fairness availability and observed-category checks', '',
        'No rural/urban, gender or income-group fairness experiment or fairness intervention was run. Substituting city tiers, KYC, or fabricated attributes would change the research question. The following are descriptive transaction-group checks at the frozen selected-model threshold; all are synthetic.', '',
        '| Attribute | Category | Test rows | Fraud labels | Prevalence | FPR | FNR | Alert rate |', '|---|---|---:|---:|---:|---:|---:|---:|']
    for col,info in fair['descriptive_groups'].items():
        for g in info['groups']:
            mm=g['metrics']; lines.append(f"| {col} | {g['group']} | {g['rows']} | {g['fraud_cases']} | {mm['prevalence']:.4f} | {fmt(mm['fpr'])} | {fmt(mm['fnr'])} | {mm['alert_rate']:.4f} |")
    lines += ['', 'Not Verified KYC has only 22 fraud labels and is flagged as a small group. Counts, Brier scores, discrimination metrics and 300-replicate user-cluster intervals are saved, including alert-rate differences. No approval rate is defined. City tier and KYC remain constant within each user in this cohort, but that does not supply the missing demographic definitions.', '',
        'As a mathematical matter, equal alert rates and equal error rates impose different constraints when group prevalences differ: alert_rate = TPR × prevalence + FPR × (1 − prevalence). Calibration is another distinct property. A single parity statistic cannot establish fairness. No intersectional analysis or parity intervention is justified by the requested-but-missing attributes here.', '',
        '## Answers to the original research questions', '',
        '| Question | Synthetic demonstration | Literature / official evidence | Unresolved gap |', '|---|---|---|---|',
        '| Which alternative signals predict default? | Timing contributes most by positive fixed-model ablation in this fraud run. | The supplied paper motivates alternative data but does not validate this dataset. | No default outcomes or four documented alternative-data families; no credit-default conclusion. |',
        '| SHAP/LIME versus bureau models? | Matched-case fidelity, stochastic stability, runtime and feature overlap were measured for logistic and forest fraud models. | Methods documentation is linked in README. | No genuine bureau model; explanations are not evidence of causation or correctness. |',
        '| Performance–fairness trade-offs? | Only descriptive city/KYC diagnostics are supported. | Fairness criteria impose different constraints; official conduct requirements are addressed separately. | Requested attributes and reliable real-world outcomes absent; no intervention or fairness finding. |',
        '| How does RBI affect deployment? | No deployment attempted. | The dated official-source matrix covers collection, privacy, responsibility, monitoring, recourse, classification safeguards and guidance status. | Exact regulated-entity category, product and legal processing arrangement remain unspecified. |', '',
        'Read the [regulatory evidence matrix](../reports/regulatory_evidence.md) for exact official links, dates, provisions, applicability and current verification limitations. It distinguishes binding instruments, phased rules, drafts and committee recommendations; it is not legal certification.', '',
        '## Limitations and next research step', '',
        'All findings are synthetic. Unknown generation rules may create or suppress correlations and may encode labels in apparently innocent columns. Retrospective fraud ascertainment is not dated. Post-completion descriptor availability is assumed. Grouped splitting prevents user overlap but not all possible dependence, label noise, generator leakage, or temporal drift. Seven conservative predictors deliberately omit potentially informative undocumented signals. These weak results do not show that legitimate alternative data are ineffective.', '',
        'Real credit-default research needs documented borrower/loan linkage, a pre-decision observation window, a defined and matured repayment outcome, genuine bureau comparisons and lawfully obtained demographic fields. An India claim additionally needs Indian population provenance, sampling coverage and external or prospective validation. This demonstration supplies reusable methodology and a reproducible negative/weak result, not a substitute for those data.', '',
        '## Reproduction and verification', '',
        'Run the exact commands in [README](../README.md). Models, thresholds and dependencies are saved. Results/private contains local row-linked outputs and must not be published. `scripts/verify.py` checks raw hashes, grouped split integrity, predictions, metrics, training preprocessing statistics, inference edge cases and explanation budgets. `verification.json` records the latest check outcome.']
    (OUT/'research_report.md').write_text('\n'.join(lines)+'\n')
    # Descriptive group uncertainty figure; never labeled demographic fairness.
    fig,axs=plt.subplots(1,2,figsize=(10,4))
    for ax,(col,info) in zip(axs,fair['descriptive_groups'].items()):
        groups=info['groups']; points=np.array([g['metrics']['alert_rate'] for g in groups]); bounds=np.array([[g['ci_95_user_cluster_bootstrap']['alert_rate'][k] for g in groups] for k in ['lower','upper']])
        ax.errorbar(np.arange(len(groups)),points,yerr=np.vstack([points-bounds[0],bounds[1]-points]),fmt='o',capsize=4)
        ax.set(xticks=np.arange(len(groups)),xticklabels=[g['group'] for g in groups],ylabel='Post-event review flag rate',title=col,ylim=(0,.4))
    fig.suptitle('Synthetic observed-category diagnostics; 95% user-cluster intervals'); fig.tight_layout(); figure_save(fig,'observed_group_diagnostics')
    print('Research report generated from saved measurements.')

if __name__=='__main__': main()
